/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mgmt.gui;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mgmt.dbutil.DBConnection;

/**
 *
 * @author HP
 */

public class OptionsFrame extends javax.swing.JFrame  {

    /**
     * Creates new form OptionsFrame
     */
   
     
    public OptionsFrame() {
        initComponents();
        this.setTitle(" employee application ");
        Toolkit t=Toolkit.getDefaultToolkit();
  	Image img=t.getImage("C:\\Users\\HP\\Documents\\pawan\\converter.png");
        this.setIconImage(img);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnadd = new javax.swing.JRadioButton();
        btnsearch = new javax.swing.JRadioButton();
        btnquit = new javax.swing.JRadioButton();
        btnshow = new javax.swing.JRadioButton();
        btntask = new javax.swing.JButton();
        btndelete = new javax.swing.JRadioButton();
        btnupdate = new javax.swing.JRadioButton();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("select your choice");

        buttonGroup1.add(btnadd);
        btnadd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(0, 0, 0));
        btnadd.setText("add employee");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnsearch);
        btnsearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(0, 0, 0));
        btnsearch.setText("search employee");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnquit);
        btnquit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnquit.setForeground(new java.awt.Color(0, 0, 0));
        btnquit.setText("quit");
        btnquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnshow);
        btnshow.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnshow.setForeground(new java.awt.Color(0, 0, 0));
        btnshow.setText("show all employees");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        btntask.setFont(new java.awt.Font("Dotum", 1, 24)); // NOI18N
        btntask.setForeground(new java.awt.Color(0, 0, 0));
        btntask.setText("Do Task");
        btntask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaskActionPerformed(evt);
            }
        });

        buttonGroup1.add(btndelete);
        btndelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(0, 0, 0));
        btndelete.setText("delete employees");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnupdate);
        btnupdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 0, 0));
        btnupdate.setText("update employees");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsearch)
                            .addComponent(btnadd)
                            .addComponent(btnshow)
                            .addComponent(btnquit)
                            .addComponent(btntask)
                            .addComponent(btndelete)
                            .addComponent(btnupdate))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnadd)
                .addGap(18, 18, 18)
                .addComponent(btnsearch)
                .addGap(18, 18, 18)
                .addComponent(btnshow)
                .addGap(18, 18, 18)
                .addComponent(btndelete)
                .addGap(18, 18, 18)
                .addComponent(btnupdate)
                .addGap(11, 11, 11)
                .addComponent(btnquit)
                .addGap(87, 87, 87)
                .addComponent(btntask)
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        
        

        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnshowActionPerformed

    private void btnquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_btnquitActionPerformed

    private void btntaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaskActionPerformed
      
        JFrame userchoice=null;
        boolean res=validateInput();
        if(!res)
        {
            JOptionPane.showMessageDialog(null,"please select your choice first");
        }
        if(btnadd.isSelected())
        {
            userchoice=new AddEmployeeFrame();
        }else if(btnshow.isSelected())
        {
            userchoice=new ViewAllEmployeeFrame();
        }else if(btnsearch.isSelected())
        {
            userchoice=new SearchEmployeeFrame();
        }else if(btndelete.isSelected())
        {
            userchoice=new DeleteEmployeeFrame();
        }else if(btnupdate.isSelected())
        {
            userchoice=new UpdateEmployeeFrame();
        }else
        {
            JOptionPane.showMessageDialog(null,"thanks for using app?","Quitting!",JOptionPane.INFORMATION_MESSAGE);
          
          System.exit(0);
          DBConnection.closeConnection();
        }
        userchoice.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_btntaskActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnadd;
    private javax.swing.JRadioButton btndelete;
    private javax.swing.JRadioButton btnquit;
    private javax.swing.JRadioButton btnsearch;
    private javax.swing.JRadioButton btnshow;
    private javax.swing.JButton btntask;
    private javax.swing.JRadioButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
        if(btnadd.isSelected()||btnshow.isSelected()||btnquit.isSelected()||btnsearch.isSelected()||btndelete.isSelected()||btnupdate.isSelected())
        {
            return true;
        }
        return false;
         }


}
